// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXlmf34hv61nDTa6DUpVebmBT5X0GkL6c',
    appId: '1:65970936564:web:061bb1549467b4411cdca1',
    messagingSenderId: '65970936564',
    projectId: 'student-40711',
    authDomain: 'student-40711.firebaseapp.com',
    storageBucket: 'student-40711.firebasestorage.app',
    measurementId: 'G-56XPVBKZQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe-dXBi5K-L5Ez-hemabeW2wvXNrXstxc',
    appId: '1:65970936564:android:1bca0bc202f99d2d1cdca1',
    messagingSenderId: '65970936564',
    projectId: 'student-40711',
    storageBucket: 'student-40711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOBKsOtnoA1UTHwSGflRy-P9JwvjDrqvU',
    appId: '1:65970936564:ios:ce4280446f85d9701cdca1',
    messagingSenderId: '65970936564',
    projectId: 'student-40711',
    storageBucket: 'student-40711.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOBKsOtnoA1UTHwSGflRy-P9JwvjDrqvU',
    appId: '1:65970936564:ios:ce4280446f85d9701cdca1',
    messagingSenderId: '65970936564',
    projectId: 'student-40711',
    storageBucket: 'student-40711.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXlmf34hv61nDTa6DUpVebmBT5X0GkL6c',
    appId: '1:65970936564:web:1db03bea1f2bed5b1cdca1',
    messagingSenderId: '65970936564',
    projectId: 'student-40711',
    authDomain: 'student-40711.firebaseapp.com',
    storageBucket: 'student-40711.firebasestorage.app',
    measurementId: 'G-PY1KEXSZJK',
  );
}
